# Valid TOML config file
data-path="/usr/app/data" # Path

# Network
bootnodes=["enode://543212b97e9da2fac17cca62c67c2909648f5e9e0247fd161622926865fbe25d75f35f0e34e9faaf7f8ce2b11e5fc3b7764b37dbaccca482a3084790eaee84ba@127.0.0.1:30303"]

rpc-http-enabled=true
rpc-http-api=["ETH","NET","IBFT"]
rpc-http-port=8548

p2p-port=30306

host-allowlist=["*"]

rpc-http-cors-origins=["all"]

# Chain
genesis-file="/usr/app/genesis.json" # Path to the custom genesis file
